---
- name: Install VLC Media Player
  tags: [video]
  community.general.flatpak:
    name: org.videolan.VLC
    state: present

- name: Install OBS Studio
  tags: [video]
  community.general.flatpak:
    name: com.obsproject.Studio
    state: present

- name: Install other video utilities
  tags: [gnome]
  ansible.builtin.dnf:
    name:
      - ffmpeg-free
