---
- name: Add nerd-fonts COPR
  tags: [terminal]
  community.general.copr:
    name: aquacash5/nerd-fonts
    state: enabled

- name: Install nerd fonts
  tags: [terminal]
  ansible.builtin.dnf:
    name:
      - terminus-nerd-fonts
      - overpass-nerd-fonts
      - iosevka-nerd-fonts
      - iosevka-term-nerd-fonts
      - jet-brains-mono-nerd-fonts
    state: present

- name: Add Starship COPR
  tags: [terminal]
  community.general.copr:
    name: atim/starship
    state: enabled

- name: Install Starship Shell Prompt
  tags: [terminal]
  ansible.builtin.dnf:
    name: starship
    state: present

- name: Add Starship to Profiles
  tags: [terminal]
  become: false
  become_user: '{{ username }}'
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: eval "$(starship init bash)"
